export const SAGA_GET_EXERCISE_TEMPLATE_LIST = 'SAGA_GET_EXERCISE_TEMPLATE_LIST'
export const SAGA_CREATE_EXERCISE_TEMPLATE = 'SAGA_CREATE_EXERCISE_TEMPLATE'
export const SAGA_EDIT_EXERCISE_TEMPLATE = 'SAGA_EDIT_EXERCISE_TEMPLATE'

export const FETCH_GET_EXERCISE_TEMPLATE_LIST = 'FETCH_GET_EXERCISE_TEMPLATE_LIST'
export const FETCH_CURRENT_EXERCISE_TEMPLATE = 'FETCH_CURRENT_EXERCISE_TEMPLATE'

export const SHOW_CREATE_EXERCISE_TEMPLATE_MODAL = 'SHOW_CREATE_EXERCISE_TEMPLATE_MODAL'
export const HIDE_CREATE_EXERCISE_TEMPLATE_MODAL = 'HIDE_CREATE_EXERCISE_TEMPLATE_MODAL'

export const SHOW_EDIT_EXERCISE_TEMPLATE_MODAL = 'SHOW_EDIT_EXERCISE_TEMPLATE_MODAL'
export const HIDE_EDIT_EXERCISE_TEMPLATE_MODAL = 'HIDE_EDIT_EXERCISE_TEMPLATE_MODAL'
