export const SAGA_CREATE_EXERCISE = 'SAGA_CREATE_EXERCISE'
export const SAGA_EDIT_EXERCISE = 'SAGA_EDIT_EXERCISE'
export const SAGA_DELETE_EXERCISE = 'SAGA_DELETE_EXERCISE'

export const FETCH_CURRENT_EXERCISE = 'FETCH_CURRENT_EXERCISE'

export const SHOW_EDIT_EXERCISE_MODAL = 'SHOW_EDIT_EXERCISE_MODAL'
export const HIDE_EDIT_EXERCISE_MODAL = 'HIDE_EDIT_EXERCISE_MODAL'
