export const SAGA_PLAN_LIST = 'SAGA_PLAN_LIST'
export const SAGA_ADD_MORNING_TRAINING_PLAN = 'SAGA_ADD_MORNING_TRAINING_PLAN'
export const SAGA_ADD_DAY_TRAINING_PLAN = 'SAGA_ADD_DAY_TRAINING_PLAN'
export const SAGA_REMOVE_TRAINING_PLAN = 'SAGA_REMOVE_TRAINING_PLAN'

export const FETCH_PLAN_LIST = 'FETCH_PLAN_LIST'
export const FETCH_CURRENT_PLAN_LIST = 'FETCH_CURRENT_PLAN_LIST'
