export const SAGA_PRESSURE_LIST = 'SAGA_PRESSURE_LIST'
export const SAGA_CREATE_PRESSURE = 'SAGA_CREATE_PRESSURE'

export const FETCH_PRESSURE_LIST = 'FETCH_PRESSURE_LIST'
export const FETCH_CURRENT_PRESSURE = 'FETCH_CURRENT_PRESSURE'

export const SHOW_CREATE_PRESSURE_MODAL = 'SHOW_CREATE_PRESSURE_MODAL'
export const HIDE_CREATE_PRESSURE_MODAL = 'HIDE_CREATE_PRESSURE_MODAL'
