export const SAGA_GET_TRAINING_LIST = 'SAGA_GET_TRAINING_LIST'
export const SAGA_CREATE_TRAINING = 'SAGA_CREATE_TRAINING'
export const SAGA_EDIT_TRAINING = 'SAGA_EDIT_TRAINING'
export const SAGA_DELETE_TRAINING = 'SAGA_DELETE_TRAINING'

export const FETCH_GET_TRAINING_LIST = 'FETCH_GET_TRAINING_LIST'
export const FETCH_CURRENT_TRAINING = 'FETCH_CURRENT_TRAINING'

export const SHOW_CREATE_TRAINING_MODAL = 'SHOW_CREATE_TRAINING_MODAL'
export const HIDE_CREATE_TRAINING_MODAL = 'HIDE_CREATE_TRAINING_MODAL'

export const SHOW_EDIT_TRAINING_MODAL = 'SHOW_EDIT_TRAINING_MODAL'
export const HIDE_EDIT_TRAINING_MODAL = 'HIDE_EDIT_TRAINING_MODAL'
